name: ToggleMod
main: me.superischroma.threatpanel.ThreatPanel
version: 1.0.1
depend: [Aero]
author: [Super_]
commands:
    togglemod:
        description: Main command for the ToggleMod.
        usage: /<command> [access | close | number]
        aliases: [trp,threatpanel,threatp,tpanel]